### ISSUE TITLE
Strange results with expand parameter of dodgr_streetnet

### ISSUE THREAD

**Issue by agila5** [ATFutures/dodgr#110]
Hi! I'm reading the vignettes of `dodgr` and running the code. I'm facing something strange when I run the code associated to `expand` parameter in the `dodgr_streetnet` function. This is the code and the corresponding result: 

``` r
library(dodgr)

bb <- osmdata::getbb("york uk")
npts <- 100
set.seed(123)
xy <- apply(bb, 1, function(i) min(i) + runif(npts) * diff(i))
routed_points <- function(expand, pts) {
  gr0 <- weight_streetnet(dodgr_streetnet(pts = pts, expand = expand))
  d0 <- dodgr_dists(gr0, from = pts)
  length(which(is.na(d0))) / length(d0)
}

vapply(
  c(0, 0.05, 0.1, 0.2), 
  function(i) routed_points(i, pts = xy),
  numeric(1)
)
#> The following highway types are present in data yet lack corresponding weight_profile values: construction, road, raceway, corridor, NA, rest_area, bus_stop, 
#> .....
#> [1] 0.017639928 0.020266876 0.023185041 0.008959434
```

<sup>Created on 2019-09-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I don't get why to a larger bbox expanded by a bigger expand parameter value corresponds less points such that it was possible to calculate a pairwise distance.

**Comment by mpadge** [comment]
That result is the total number of points able to be reached within the network, which should decrease as `expand` increases. That is exactly what you get overall, *but* it is statistically noisy. I also re-ran that example recently and got similarly irregular results to yours. It's all just statistical noise. Although this is something I maybe should modify so that example makes more sense, it is nevertheless relatively low importance at the moment, so am going to close this. Thanks!
