### ISSUE TITLE
Name of dodgr_sf is confusing

### ISSUE THREAD

**Issue by Robinlovelace** [ATFutures/dodgr#43]
Because it returns an object of class:

```
"sfc_LINESTRING" "sfc"           
```

Suggestions: rename it to `dodgr_sfc` and create a new function `dodgr_sf` that returns an object of class `sf`.

**Comment by mpadge** [comment]
Hard to do `dodgr_sf` without importing full `sf` dependency, so would prefer not to do that, but will definitely do the rename to `dodgr_to_sfc`

**Comment by mdsumner** [comment]
fwiw I've toyed with the idea of an "sf()" driver (and others)

```r
your_model_goes_here %>% some_stuff() %>% sf() ## out pops that format! (Why not sfc() too)

```

It's implemented in spbabel for sp(), and silicate is now vastly more ready for that kind of thing to be reworked.  I turned it off in spbabel because I couldn't get the general case working right for sfc, adding the attributes and class for sf is not hard.

That's my long way of saying, let's do it but not here.  I still have a few things to square away before getting to it again.

**Comment by mpadge** [comment]
yeah, i hadn't yet thought that far along. Converting to `sfc` is easy, but `silicate` is really going to need an `sc_sf()` that ideally works without a heavy `sf` dep, so that'll be the perfect place to develop that. Or maybe even a separate `to_sf` package that does not actually have `sf` dep, yet converts most common forms (`sp`, `igraph`, `raster`, `tidygraph`, `dodgr`, plain old bloody `data.frame `objects that don't have a projection).

**Comment by mdsumner** [comment]
I'm obsessed with something like `ggplot(d, aes(lon, lat, group = path, id = object)) %>% to_sf()`  - it works great for tracking data, because the topology is easy `d %>% arrange(time) %>% group_by(tag) %>% select_coords(lon, lat, time) %>%  to_trip()` - but there's a few things needed and ggplot2 inherently doesn't work with edges, so the idioms aren't there, well aes() is basically select_coords.

I think we could forget polygons for a bit and find a bridge between transport packages and trip and what ggplot2 can do, all this is active on my mind :)

**Comment by mpadge** [comment]
Re-opened until full deprecation at version 0.1.2
