### ISSUE TITLE
weight_streetnet does not support alternative geometry column names for sf data.frames

### ISSUE THREAD

**Issue by mem48** [ATFutures/dodgr#66]
Minor Bug:

`SF` supports geometry columns with different names and often uses `geom` as the geometry column. But `weight_streetnet` returns the error.

```
Error in dodgr::weight_streetnet(rail, type_col = "type", wt_profile = wts,  : 
  sf_lines must be class "sf" and have a geometry column
```

Unless the geometry column is called "geometry"

**Comment by mpadge** [comment]
Yeah, I've been aware of that one for a while, but kinda shuffled it into the "wait until someone complains" drawer. You're usually the first one these days, so ... I guess I'd better get on to that.

**Comment by mdsumner** [comment]
I've used a few sneaky ` attr(x, "sf_column")` here and there. The complementary case is a data frame with a geometry column but it's not of class "sf". That bites when trying to subset sf, without sf loaded, the class is dropped - I've partly worked around that somewhere. Always interested in different approaches!

**Comment by mpadge** [comment]
That commit is mostly a hack, but at least now allows this:
```
> gcol <- grep ("geometry", names (hampi))
> names (hampi)[gcol] <- "geom" # or anything that greps "geom"
> net <- weight_streetnet (hampi) # okay
> names (hampi)[gcol] <- "g" # plus can also be "g"
> net <- weight_streetnet (hampi) # also okay
> names (hampi)[gcol] <- "gg" # but currently nothing else
> net <- weight_streetnet (hampi)
Error in get_sf_geom_col(x) : Unable to determine geometry column
```
Not the smartest solution, but should cover most use cases. Agreed @mem48?

@mdsumner I've still got `weight_streetnet.default() -> stop("Unknown class")`, so still has to be "sf". At the moment, I don't see any real utility of allowing `sf` structures without the class label to be passed here, but feel free to convince otherwise. The whole handling of classes will likely change with the imminent development of `weight_streetnet.sc` anyway.

**Comment by mdsumner** [comment]
All good, my thought there was a sidetrack 👍

**Comment by mpadge** [comment]
BTW, subsetting without `sf` loaded *usually* works as long as you
```
x [, , drop = TRUE]
```
(and then explicitly revert the attributes where necessary)
